volumes:
  rabbit_mqdata:
    driver: local
  accounts_pd_data:


services:
  accounts_db:
    image: postgres:latest
    env_file: ../accounts/.env
    volumes:
      - accounts_pd_data:/var/lib/postgresql/data/
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  gateway:
    build: ../gateway/.
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  accounts:
    build: ../accounts/.
    env_file:
      - ../accounts/.env
    restart: always
    depends_on:
      - rabbitmq
      - accounts_db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:8001"
    depends_on:
      - gateway
      - accounts
